import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv.includes("--watch");

esbuild
  .context({
    banner: { js: banner },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron"],
    format: "cjs",
    target: "es2016",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
  })
  .then((ctx) => {
    if (watch) {
      ctx.watch();
    } else {
      ctx.rebuild().then(() => ctx.dispose());
    }
  })
  .catch(() => process.exit(1));
